// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj4QJ7psbUNEpDbElZhWIFlF5f9RyZSys',
    appId: '1:488679738203:web:f20af3b3ecf2bf7ef7e87e',
    messagingSenderId: '488679738203',
    projectId: 'yum-yum-db',
    authDomain: 'yum-yum-db.firebaseapp.com',
    storageBucket: 'yum-yum-db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXqPu2rRxGMsZf8M9lK5RKBxiDNPtNSQs',
    appId: '1:488679738203:android:ffb5ec1d145a5c07f7e87e',
    messagingSenderId: '488679738203',
    projectId: 'yum-yum-db',
    storageBucket: 'yum-yum-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpSdHpwGTNEpan7IpyyDKNhGTzzuyy2bg',
    appId: '1:488679738203:ios:5072c8526113f325f7e87e',
    messagingSenderId: '488679738203',
    projectId: 'yum-yum-db',
    storageBucket: 'yum-yum-db.firebasestorage.app',
    iosBundleId: 'com.example.yumYum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpSdHpwGTNEpan7IpyyDKNhGTzzuyy2bg',
    appId: '1:488679738203:ios:5072c8526113f325f7e87e',
    messagingSenderId: '488679738203',
    projectId: 'yum-yum-db',
    storageBucket: 'yum-yum-db.firebasestorage.app',
    iosBundleId: 'com.example.yumYum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj4QJ7psbUNEpDbElZhWIFlF5f9RyZSys',
    appId: '1:488679738203:web:bd122425581e9b6bf7e87e',
    messagingSenderId: '488679738203',
    projectId: 'yum-yum-db',
    authDomain: 'yum-yum-db.firebaseapp.com',
    storageBucket: 'yum-yum-db.firebasestorage.app',
  );

}